name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 12 * * *' # Runs every day, 12:00 UTC
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://lesleylai.info/rss.xml"
          max_post_count: 5
          template: "- [$title]($url) ($date)$newline"
          date_format: dddd, yyyy dd mmmm
          tag_post_pre_newline: true
